### ISSUE TITLE
TypeError: is_hotkey_registered() got an unexpected keyword argument 'hotkey' 

### ISSUE THREAD

**Issue by alxtrade** [opentensor/text-prompting#66]
TypeError: is_hotkey_registered() got an unexpected keyword argument 'hotkey'  in run.py. Won't let the miner start 
![IMG_6499](https://github.com/opentensor/text-prompting/assets/56977792/3801b5cc-05e4-4c36-8179-225efbbdbd2a)

**Comment by p-ferreira** [comment]
Hello @alxtrade! Thank you very much for bringing this up.
This bug was fixed in the PR #61 and will be later released today in version `2.1.2` ;)
